### ISSUE TITLE
BuildQualityChecks Fails Waiting On Log From Later Build Task

### ISSUE THREAD

**Issue by VannaDii** [almtcger/VstsExtensions#2] opened 2017-08-24 14:07 UTC
The BuildQualityChecks task appears to assume usage of the logs from the last build task in the process. Attempting to use this task prior to the last build task will result in a timeout waiting for the logs of the last build task (which are never available).

**Example 1** (works):

1. ... Others Tasks ...
2. Build Task
3. BuildQualityChecks Task

**Example 2** (fails):

1. ... Others Tasks ...
2. Build Task
3. BuildQualityChecks Task
4. ... Other Tasks ...
5. Build Task

**Comment by almtcger** [comment] 2017-09-27 12:50
Hi GioCirque,

sorry for the very late response. We usually don't check the issues on GitHub regularly since we use the repo only for our documentation. We'll keep an eye on the issues in the future.

The BuildQualityChecks task should work even if additional build tasks run after it. It won't be able to see warnings or code coverage for later tasks, but it should not wait for their log information. Could you please tell me which version of the task you're using? It would also be great if you ran the build with the variable System.Debug set to true and sent the task log file to our support email address [PSGerExtSupport@microsoft.com](mailto:PSGerExtSupport@microsoft.com).

**Comment by almtcger** [comment] 2018-01-19 11:18
Closing this issue for now since we cannot reproduce it. If the problem arises again, please contact us at PSGerExtSupport@microsoft.com and sind in the task log file as mentioned above.

**Closed as completed by almtcger** 2018-01-19 11:18 UTC
