### ISSUE TITLE
No changes but warnings count increases

### ISSUE THREAD

**Issue by harrybin** [almtcger/VstsExtensions#4] opened 2017-10-18 05:20 UTC
the warnings count changes although there no change:

Associated changes
   No changes associated with this build.
Build Quality Checks
   Build
   The number of warnings (1126) has increased since the previous build! The previous build had 1125 
 warning(s).
Warning Statistics
   Warnings haven't changed since last build.

Our warning filter is: /(\d+)\s+Warning\(s\)/i
It's a build of usual .net C# solutions.

**Comment by almtcger** [comment] 2017-10-18 07:40
Hi Harry,

thanks for reporting this. I believe the problem is caused by an additional warning from the build infrastructure that is not a compiler warning, but it's hard to say without more information. Could you please send us a screenshot of the build summary page for the current build (with 1126 warnings) and the previous build (with 1125 warnings) to our support address PSGerExtSupport@microsoft.com.

**Comment by almtcger** [comment] 2017-10-19 21:34
We close this issue since the warning count actually was correct. The statistics message "Warnings haven't changed..." is misleading, since the analysis could not see the warnings due to the special warnings filter used in the task configuration.

We'll fix the message and make sure that it reflects the change in the warning count with one of the next extension updates.

**Closed as completed by almtcger** 2017-10-19 21:34 UTC
