### ISSUE TITLE
Tasks ends with error

### ISSUE THREAD

**Issue by PArpagaus** [almtcger/VstsExtensions#5] opened 2018-01-03 13:32 UTC
In some Team Projects this tasks ends with an error "TF400714: File ID 0 not found", in other Team Projects it works fine. We think, that this tasks crashes after a cretain amount of warnings in the projects.

2017-12-29T15:14:28.7574046Z ##[section]Finishing: Build projects $(Build.SourcesDirectory)/99_Development/Configurations/BuildDefinition.xml
2017-12-29T15:14:28.7730319Z ##[section]Starting: Check build quality
2017-12-29T15:14:28.7730319Z ==============================================================================
2017-12-29T15:14:28.7730319Z Task         : Build Quality Checks
2017-12-29T15:14:28.7730319Z Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
2017-12-29T15:14:28.7730319Z Version      : 2.9.0
2017-12-29T15:14:28.7730319Z Author       : Microsoft Premier Services
2017-12-29T15:14:28.7730319Z Help         : [[Docs]](https://github.com/almtcger/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
2017-12-29T15:14:28.7730319Z ==============================================================================
2017-12-29T15:14:29.3199422Z SystemVssConnection exists true
2017-12-29T15:14:29.6168371Z Validating build warnings policy...
2017-12-29T15:14:29.6480889Z Counting warnings from tasks:
2017-12-29T15:14:29.6480889Z - Build projects $(build.sourcesDirectory)/99_Development/Configurations/BuildDefinition.xml
**2017-12-29T15:14:30.0231334Z TF400714: File ID 0 not found.**
2017-12-29T15:14:30.0231334Z ##[error]At least one build quality policy was violated. See Build Quality Checks section for more details.
2017-12-29T15:14:30.0231334Z ##[section]Finishing: Check build quality
2017-12-29T15:14:30.0231334Z ##[section]Starting: Post Job Cleanup
2017-12-29T15:14:30.0387422Z ##[section]Finishing: Post Job Cleanup
2017-12-29T15:14:30.0387422Z ##[section]Finishing: Build

**Comment by almtcger** [comment] 2018-01-03 14:25
Hi PArpagaus,

could you please run your build again with the variable System.Debug set to true and send the build log to PSGerExtSupport@microsoft.com?

What makes you think that the issue is related to the number of warnings? We have successfully tested the task with up to 10,000 warnings and haven't found any issues. To me it looks as if the error occurs when our task tries to upload the task result markdown file. The debug log will hopefully show enough information to solve this.

Thanks
René

**Comment by almtcger** [comment] 2018-01-19 11:16
We cannot reproduce the issue so we're closing this for now. If the problem arises again, please send in the log as discussed via email and we will continue to investigate.

**Closed as completed by almtcger** 2018-01-19 11:16 UTC
